### ISSUE TITLE
Adicionar suporte à múltiplas medições para medidas mais estáveis

### ISSUE THREAD

**Issue by LincolnMA** [LincolnMA/vna_communication#3]
Suporte para que seja possível mudar o parâmetro valuesPerFrequency para que seja possível fazer a média de vários sweeps consecutivos para alcançar um valor mais estável.

**Comment by El-Tomaz** [comment]
Pra fazer a média de S11 e S21 é só fazer da mesma forma que a gente faria com números complexos normais ? 
por exemplo: 
[(a + bi) + (c+di)] / 2

**Comment by LincolnMA** [comment]
Gabriel, segundo a documentação, quando valuesPerFrequency for igual a 1, não existem repetições durante o processo de envio dos pontos. No código cada um dos pontos de medição tem 32 bytes de informação e ficam armazenados em sequência em uma lista de pontos: [p0,p1,p2,p3,...]. Caso o valor de valuesPerFrequency seja 2, por exemplo, o VNA faz duas medições consecutivas para cada frequência, ficando: [p0,p0,p1,p1,p2,p2,...]. Dessa forma, o nosso código deve ser capaz de fazer uma média dos valores de p0, p1, p2, etc. Assim, poderemos conseguir uma medição mais estável caso seja necessário.

**Comment by El-Tomaz** [comment]
Outra dúvida que surgiu foi : os dados já vem ordenados sempre ? por exemplo, vamos dizer que vá fazer duas medições pra cada valor de frequência: os dados chegariam ```[po,po,p1,p1,...]``` ou eles poderiam vir desordenados tipo ```[p0,p2,p0,p1,...]``` por que isso pode ser contornado já que nos bytes de cada leitura tem um campo freqIndex que diz o índice da mediçao né, então daria pra checar sobre qual frequência aqueles dados se referem. Mas se eles já vierem ordenados sempre seria bem mais simples.

**Comment by Erik-Silva** [comment]
Quando alteramos o número de pontos por frequência o código fica parado aqui 
https://github.com/LincolnMA/vna_communication/blob/d47e2c353e3b8695ee966a906cbf565b4fc27e79/nanovna.py#L113. 

Acho estranho o tempo que leva para realizar as medidas, note que por exemplo ao realizar uma solicitação com número de frequências igual a 2, há uma demora desproporcional, até para dar erro.

Não é algo correlacionado ao delay explícito que é escrito na tela quando rodamos o código.

Não encontrei um delay específico dentro de algum loop que justificasse tal demora, há algum e eu não vi?

**Comment by El-Tomaz** [comment]
Boa noite professor. Pelo que vi da sua mensagem em algum momento surgiu uma mensagem de erro, se sim daria pra compartilhar aqui ? Além disso, sabe dizer se esse comportamento já tinha ocorrido antes, ou foi depois de algum commit específico ? Como não tenho o equipamento em mãos fica difícil reproduzir o erro, mas com essas informações daria pra adiantar. O código não tem nenhum delay explícito ou intencional, tudo é fruto do timing da comunicação serial (que é o principal gargalo) mas que mesmo assim não deveria ultrapassar alguns segundos (depende da resolução das medidas e da quantidade de médias é claro). Vou upar um código que debugue algumas informações nesse loop, já que o erro parece estar aí
